In [11]:
import numpy as np
import pandas as pd

In [12]:
df2 = pd.read_csv(r'C:\Users\aalgo\OneDrive\Desktop\Olist_Real_Data_EDA_Practice\Data\olist_order_payments_dataset.csv')

In [13]:
df2.shape

(103886, 5)

In [14]:
df2.size

519430

In [15]:
df2.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [16]:
df2.head()
df2.sample(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
52626,ec72beff33dc025a12ecdb790a99f730,1,boleto,1,84.03
32956,4998304ddcd450f9750a4de8f7933296,1,credit_card,1,82.61
92395,76031077492a53bea99bb3eb41516b94,1,boleto,1,113.62
12457,1c8453ac180e833c992dc135bd9302c5,1,credit_card,1,116.84
38552,98f75acaf1c9b0c2424f3b0fc6a22bdc,1,credit_card,7,74.07

* Q6. Calculate the standard deviation and variance of payment_value from order_payments. What does the std tell you about price spread?Markdo

In [17]:
payment = df2['payment_value'].to_numpy()
type(payment)

numpy.ndarray

In [18]:
payment.std()

np.float64(217.49301707022238)

In [19]:
payment.var()

np.float64(47303.21247430804)

* Q7. Find the 25th, 50th, 75th, and 90th percentiles of the price column using np.percentile()

In [28]:
df = pd.read_csv(r'C:\Users\aalgo\OneDrive\Desktop\Olist_Real_Data_EDA_Practice\Data\olist_order_items_dataset.csv')

In [29]:
price = df['price'].to_numpy()

In [30]:
type(price)

numpy.ndarray

In [33]:
print(np.percentile(price,25))
print(np.percentile(price,50))
print(np.percentile(price,75))
print(np.percentile(price,90))

39.9
74.99
134.9
229.8

* Q8. Normalize the price column to a 0–1 scale using min-max normalization: (x - min) / (max - min).
Print the first 10 normalized values.
💡 Hint: NumPy makes this a one-liner with broadcasting

In [38]:
norm = (price-price.max()) / (price.max() - price.min())

In [39]:
norm

array([-0.99137976, -0.96450183, -0.97057535, ..., -0.98529139,
       -0.99181188, -0.99374086], shape=(112650,))