In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\aalgo\Olist_Real_Data_EDA_Practice\Data\olist_order_payments_dataset.csv')

In [14]:
df.shape

(103886, 5)

In [17]:
df.size

519430

In [18]:
df.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [21]:
df.head()
df.sample(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
50365,c3172e32bc52d8dde2aa5c6cb36cddfd,1,boleto,1,127.45
59372,098fa8e236952567d948321ee4684854,5,voucher,1,22.35
79470,690ce80c28087f2dc808a71e7ea057fd,1,credit_card,2,105.56
12443,b92e445b2b63be72a4cd1001e20826bd,1,credit_card,10,176.76
97596,7ea04d381a2ba7d7f14be55b878830a5,1,credit_card,7,2060.20

* Q6. Calculate the standard deviation and variance of payment_value from order_payments. What does the std tell you about price spread?Markdo

In [24]:
payment = df['payment_value'].to_numpy()
type(payment)

numpy.ndarray

In [25]:
payment.std()

np.float64(217.49301707022238)

In [26]:
payment.var()

np.float64(47303.21247430804)